version: '3.8'

services:
  # Reverse proxy, Caddy
  caddy:
    image: caddy
    restart: unless-stopped
    container_name: caddy
    networks:
      - revolt
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'

  # MongoDB server
  database:
    image: mongo:5
    restart: unless-stopped
    networks:
      - revolt
    volumes:
      - revolt-production:/data/db

  # Redis server
  redis:
    image: eqalpha/keydb
    restart: unless-stopped
    networks:
      - revolt

  # REVOLT API server (Delta)
  api:
    image: revoltchat/server:master
    restart: unless-stopped
    depends_on:
      - database
      - redis
    networks:
      - revolt
    env_file: .env
    environment:
      - REVOLT_MONGO_URI=mongodb://database
      - REVOLT_REDIS_URI=redis://redis/

  # REVOLT Web App
  web:
    image: revoltchat/client:master
    restart: unless-stopped
    networks:
      - revolt
    env_file: .env

  # S3-compatible storage server
  minio:
    image: minio/minio:RELEASE.2021-11-03T03-36-36Z
    restart: unless-stopped
    networks:
      - revolt
    volumes:
      - minio-production:/data
    env_file: .env
    command: server /data

  # Create buckets for minio.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - revolt
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      while ! curl -s --output /dev/null --connect-timeout 1 http://minio:9000; do echo 'Waiting minio...' && sleep 0.1; done;
      /usr/bin/mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb minio/attachments;
      /usr/bin/mc mb minio/avatars;
      /usr/bin/mc mb minio/backgrounds;
      /usr/bin/mc mb minio/icons;
      /usr/bin/mc mb minio/banners;
      exit 0;
      "

  # REVOLT file hosting service (Autumn)
  autumn:
    image: revoltchat/autumn:master
    restart: unless-stopped
    env_file: .env
    depends_on:
      - database
      - createbuckets
    networks:
      - revolt
    environment:
      - AUTUMN_MONGO_URI=mongodb://database

  # REVOLT metadata and image proxy (January)
  january:
    image: revoltchat/january:master
    restart: unless-stopped
    networks:
      - revolt

networks:
  revolt:

volumes:
  revolt-production:
  minio-production:
