---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    revolt-helm.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      revolt-helm.service: redis
  template:
    metadata:
      labels:
        revolt-helm.service: redis
    spec:
      containers:
        - image: docker.io/eqalpha/keydb
          name: redis
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    revolt-helm.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    revolt-helm.service: redis
  type: ClusterIP
