---
apiVersion: v1
data:
  HOSTNAME: {{ .Values.externalName }}
  REVOLT_PUBLIC_URL: https://{{ .Values.externalName }}/api
kind: ConfigMap
metadata:
  labels:
    revolt-helm.service: web
  name: web-cm-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    revolt-helm.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      revolt-helm.service: web
  template:
    metadata:
      labels:
        revolt-helm.service: web
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: web-cm-env
          image: ghcr.io/revoltchat/client:master
          name: web
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    revolt-helm.service: web
  name: web
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    revolt-helm.service: web
  type: ClusterIP
